"""updated migrations

Revision ID: 505614d94a3a
Revises: 15be4143ba7e
Create Date: 2026-06-28 01:55:04.835310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '505614d94a3a'
down_revision: Union[str, Sequence[str], None] = '15be4143ba7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_idx', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_level', sa.Integer(), nullable=True),
    sa.Column('list_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_document_id'), 'blocks', ['document_id'], unique=False)
    op.create_table('tables',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('sheet_no', sa.Integer(), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('table_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('sample_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_tables_document_id'), 'tables', ['document_id'], unique=False)
    op.create_table('table_rows',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('row_idx', sa.Integer(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_rows_table_id'), 'table_rows', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_rows_table_id'), table_name='table_rows')
    op.drop_table('table_rows')
    op.drop_index(op.f('ix_tables_document_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_blocks_document_id'), table_name='blocks')
    op.drop_table('blocks')
    # ### end Alembic commands ###
