"""model update

Revision ID: 57ff7d427ff4
Revises: ad0ae9421017
Create Date: 2026-06-30 23:29:33.924676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57ff7d427ff4'
down_revision: Union[str, Sequence[str], None] = 'ad0ae9421017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('anchors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('tables', 'origin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('origin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tables', 'anchors')
    # ### end Alembic commands ###
