"""update models

Revision ID: a47dfeb7f03a
Revises: b2f1a9c4d7e3
Create Date: 2026-07-01 22:45:53.745506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47dfeb7f03a'
down_revision: Union[str, Sequence[str], None] = 'b2f1a9c4d7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_embedding'), table_name='content', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_content_search_text_trgm'), table_name='content', postgresql_ops={'search_text': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_content_search_text_trgm'), 'content', ['search_text'], unique=False, postgresql_ops={'search_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_content_embedding'), 'content', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
