"""library ingest elapsed seconds

Revision ID: a8d720c477fb
Revises: d05abcf71e1c
Create Date: 2026-08-16 14:27:14.164464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d720c477fb'
down_revision: Union[str, Sequence[str], None] = 'd05abcf71e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libraries', sa.Column('ingest_elapsed_seconds', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libraries', 'ingest_elapsed_seconds')
    # ### end Alembic commands ###
