"""update models

Revision ID: c02bc6cc5b3b
Revises: 13cc7b1e714c
Create Date: 2026-07-06 20:33:07.447898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02bc6cc5b3b'
down_revision: Union[str, Sequence[str], None] = '13cc7b1e714c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libraries', sa.Column('embed_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libraries', 'embed_started_at')
    # ### end Alembic commands ###
