"""drop content token_count column

Revision ID: d05abcf71e1c
Revises: 000000000003
Create Date: 2026-08-10 22:39:04.519980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05abcf71e1c'
down_revision: Union[str, Sequence[str], None] = '000000000003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'token_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
